---
- hosts: all
  become: yes
  tasks:
  - name: template1 with dynamic machine name
    template:
      src: firsttemplate.j2
      dest: /home/ansible/templates
 - name: template2 with dynamic machine name
    template:
      src: secondtemplate.j2
      dest: /home/ansible/templates1
