---
- hosts: Ubuntu
  become: yes
  tasks:
  - name: template1 with dynamic machine name
    template:
      src: firsttemplate.j2
      dest: /home/ansible/templates
  - name: template2 with dynamic machine name
    template:
      src: secondtemplate.j2
      dest: /home/ansible/templates1
  - name: tomcat7 default settings
    template:
      src: tomcat7.j2
      dest: /etc/default/tomcat7
    notify:
    - restart tomcat
    handlers:
    - name: restart tomcat
      service:
        name: tomcat7
        state: restarted

